package javaapplication1;


import java.awt.Point;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2
 */
public class MiniProject extends javax.swing.JFrame {
       public      int  qt=0; 
    public      int  pr=0;
      String path="";
            String newPath="";
 public ArrayList<Users> listUsers =new ArrayList<Users>();;
    private Point mouseClickPoint; // Will reference to the last pressing (not clicking) position

    /**
     * Creates new form MiniProject
     */
       
                Conx c=new Conx();

    public MiniProject() throws ClassNotFoundException, SQLException {
                         //   c.updateProduit( 254,"dxdd",2,2 ,"dd",1);

        initComponents();
    // adding components

this.setSize(950,620);

c.updateProduit( 277,"",11,11 ,"","");

              Conx c = null;
                    try {
                        c = new Conx();

                       jTable1.setModel(c.selectProduit());
                           jTable1.setRowHeight(150);
//lire image 
    jTable1.getColumnModel().getColumn(7).setCellRenderer(new ImageRenderer());
        jTable1.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);

jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
 jTable1.repaint();
  jTable1.revalidate();
  Vector comboBoxItems=new Vector();
  int n =c.getUsers().size();
   
  listUsers=c.getUsers();
  for (int j=1 ;j< n;j++){
      comboBoxItems.add(listUsers.get(j).getLogin());
  }
  DefaultComboBoxModel modelUsers = new DefaultComboBoxModel(comboBoxItems);
ListeName.setModel(modelUsers);
  Vector comboBoxItemsFour=new Vector();
  DefaultComboBoxModel model2 = new DefaultComboBoxModel(comboBoxItemsFour);

comboBoxItemsFour.add("Mohammed");
comboBoxItemsFour.add("anis");
comboBoxItemsFour.add("fahmi");
comboBoxItemsFour.add("oussama");
comboBoxItemsFour.add("hamdi");
comboBoxItemsFour.add("khaled");

jComboBox1.setModel(model2);

 



        //           jTable1.getColumnModel().getColumn(6).sizeWidthToFit();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
                    }
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Produits = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Supp = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Rf = new javax.swing.JRadioButton();
        Rp = new javax.swing.JRadioButton();
        Rr = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        Ajouter = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        prix = new javax.swing.JTextField();
        Quantite = new javax.swing.JTextField();
        ref = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Desc = new javax.swing.JTextField();
        noml = new javax.swing.JLabel();
        prixl = new javax.swing.JLabel();
        ql = new javax.swing.JLabel();
        lr = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        Gere_Profile = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        ListeName = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        nomUpdate = new javax.swing.JTextField();
        Updatemotpasse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des produits ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setResizable(false);

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setOpaque(true);

        Produits.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Produits.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        Supp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Contols_-_Add_On-35-512_50x50.png"))); // NOI18N
        Supp.setText("supprimer produits");
        Supp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Supp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppActionPerformed(evt);
            }
        });

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/edit-button-512_240x240_50x50.png"))); // NOI18N
        Update.setText("modifier produits");
        Update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Update.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/refresh_playback_back_again_control_icon_multimedia_blue_video-512_50x50.png"))); // NOI18N
        jButton1.setText("synchronisation");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("   Produits");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        buttonGroup1.add(Rf);
        Rf.setText("Fournisseur");
        Rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RfActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rp);
        Rp.setText("Produit");

        buttonGroup1.add(Rr);
        Rr.setText("Referance");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/green-search-button-icon-69021_50x50.png"))); // NOI18N
        jButton4.setText("Recherche");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)
                                        .addGap(405, 405, 405))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(Supp)
                                        .addGap(165, 165, 165)
                                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rf)
                                .addGap(31, 31, 31)
                                .addComponent(Rp)
                                .addGap(18, 18, 18)
                                .addComponent(Rr)
                                .addGap(579, 579, 579)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rf)
                    .addComponent(Rp)
                    .addComponent(Rr))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(jButton1)
                    .addComponent(Supp))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Produits.setViewportView(jPanel1);

        jTabbedPane1.addTab("Produits", Produits);

        Ajouter.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setAutoscrolls(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("nom:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("prix");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Quantité");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("référence ");

        Add.setIcon(new javax.swing.ImageIcon("C:\\Users\\2\\Documents\\NetBeansProjects\\JavaApplication1\\image\\icon\\check-40319_1280_50x48.png")); // NOI18N
        Add.setText("      Ajouter");
        Add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });

        Quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantiteActionPerformed(evt);
            }
        });

        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Ajouter produits");

        Desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescActionPerformed(evt);
            }
        });

        noml.setForeground(new java.awt.Color(255, 0, 0));
        noml.setText("*");
        noml.setName(""); // NOI18N

        prixl.setForeground(new java.awt.Color(255, 0, 0));
        prixl.setText("*");

        ql.setForeground(new java.awt.Color(255, 0, 0));
        ql.setText("*");

        lr.setForeground(new java.awt.Color(255, 0, 0));
        lr.setText("*");
        lr.setOpaque(true);

        jButton2.setText("image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("select image");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jScrollPane3.setViewportView(jComboBox1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("fournisseur   de produit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(447, 447, 447))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(180, 180, 180)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(503, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addComponent(Desc)
                                    .addComponent(prix)
                                    .addComponent(Quantite)
                                    .addComponent(ref, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(noml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(prixl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lr, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noml)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prixl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Quantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ql))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(Add)
                .addGap(39, 39, 39))
        );

        Ajouter.setViewportView(jPanel4);

        jTabbedPane1.addTab("Ajouter", Ajouter);

        ListeName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeNameActionPerformed(evt);
            }
        });

        jButton5.setText("Supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nom:");

        jLabel9.setText("Mot passe :");

        jButton6.setText("Modifier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Activer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\2\\Desktop\\ImageJava\\icon-user-default_0_200x200.png")); // NOI18N
        jLabel11.setLabelFor(Add);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ListeName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jButton5))
                        .addGap(522, 522, 522))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomUpdate)
                            .addComponent(Updatemotpasse, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updatemotpasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addComponent(jButton6)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListeName)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addGap(167, 167, 167))
        );

        Gere_Profile.setViewportView(jPanel3);

        jTabbedPane1.addTab("Gére Profile", Gere_Profile);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// activation du compte client  
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            c.SetRole( listUsers.get(ListeName.getSelectedIndex()).getId());    
          javax.swing.JOptionPane.showMessageDialog
            (null,"compte:"+listUsers.get(ListeName.getSelectedIndex()).getId() +"est activé avec succès","modifiées",JOptionPane.INFORMATION_MESSAGE);  
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed
//change login ou mode passe de l'administrateur
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            c.setLogin(nomUpdate.getText(), Updatemotpasse.getText());
            javax.swing.JOptionPane.showMessageDialog
            (null,"votre login et mot de passe sont modifiées avec succès","modifiées",JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //        ListeName.getSelectedIndex()
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ListeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeNameActionPerformed
//chosire image 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");

        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            if(filter.accept(selectedFile)){

                path = selectedFile.getAbsolutePath();
                File save   =new SaveImage().save(path,selectedFile.getName());
                newPath=save.getPath();
                image.setIcon(new ImageIcon(newPath));
                image.repaint();
                image.revalidate();
            }else{
                JOptionPane.showMessageDialog(null," le fichier selectionné n'est pas une image  valide","Désolé, tu n'as pas rempli les champs correctement"
                    ,JOptionPane.ERROR_MESSAGE);
            }

        }
        //if the user click on save in Jfilechooser

        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescActionPerformed

    private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refActionPerformed

    private void QuantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantiteActionPerformed

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed

// verification des champs 
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        boolean prixTrue=false;
        boolean QuantiteTrue=false;
        boolean nomTrue=false;
        boolean refTrue=false;

        String messageprix="Le prix entré n'est pas valide.";
        String messageNom="Le nom entré n'est pas valide";
        String messageQuantite="Le Quantite entré n'est pas valide.";
        String messageReferance="Le réferance entre n'est pas valide.";
        try{
            Integer.parseInt(prix.getText());
            prixTrue=true;
            prixl.setText("");

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,messageprix,"Désolé, tu n'as pas rempli les champs correctement"
                ,JOptionPane.ERROR_MESSAGE);
            prixTrue=false;
            prixl.setText(messageprix);

        }

        try{
            Integer.parseInt(Quantite.getText());
            QuantiteTrue=true;
            ql.setText("");

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,messageQuantite,"Désolé, tu n'as pas rempli les champs correctement"
                ,JOptionPane.ERROR_MESSAGE);
            QuantiteTrue=false;
            ql.setText(messageQuantite);

        }

        try{
            Integer.parseInt(ref.getText());
            refTrue=true;
            lr.setText("");

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,messageReferance,"Désolé, tu n'as pas rempli les champs correctement"
                ,JOptionPane.ERROR_MESSAGE);
            refTrue=false;
            lr.setText(messageReferance);

        }
        if(Desc.getText() != ""){
            nomTrue=true;
            noml.setText("");

        }else{
            nomTrue=false;
            noml.setText(messageNom);

            JOptionPane.showMessageDialog(null,messageNom,"Désolé, tu n'as pas rempli les champs correctement"
                ,JOptionPane.ERROR_MESSAGE);
        }

        if((QuantiteTrue )&&(prixTrue)&&( nomTrue)&&(refTrue)){
            int  prixs=   Integer.parseInt(prix.getText());
            int quant= Integer.parseInt(Quantite.getText());
            String refe= ref.getText();
            String dsec=Desc.getText();

            String msg=   c.AjouterP(dsec,prixs,quant,refe,newPath,(String)jComboBox1.getSelectedItem());
            JOptionPane.showMessageDialog(null,msg,"Titre",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:$
        try {

            if(Rf.isSelected()){
                System.out.print(jTextField1.getText());

                jTable1.setModel(c.RechercheFournisseur(jTextField1.getText()));
            }else if(Rp.isSelected()){
                jTable1.setModel(c.RechercheProduit(jTextField1.getText()));

            }else{
                jTable1.setModel(c.RechercheProduit(jTextField1.getText()));

            }
            jTable1.setRowHeight(150);

            jTable1.getColumnModel().getColumn(7).setCellRenderer(new ImageRenderer());
            jTable1.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);

            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            jTable1.repaint();
            jTable1.revalidate();                     //   jTable1.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());

        } catch (SQLException ex) {
            Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void RfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RfActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            jTable1.setModel(c.selectProduit());
            jTable1.setRowHeight(150);

            jTable1.getColumnModel().getColumn(7).setCellRenderer(new ImageRenderer());
            jTable1.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);

            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            jTable1.repaint();
            jTable1.revalidate();

        } catch (SQLException ex) {
            Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        /*        Image img = null;
        try {
            img = ImageIO.read(getClass().getResource("resources/water.bmp"));
        } catch (IOException ex) {
            Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
        }

        Update.setIcon(new ImageIcon(img));  */

        int row=(int)jTable1.getSelectedRow();
        int id=(int) jTable1.getModel().getValueAt(row, 0);
        String Titre=(String)jTable1.getModel().getValueAt(row, 1);
        pr =Integer.parseInt(jTable1.getModel().getValueAt(row, 2).toString());

        qt =Integer.parseInt(jTable1.getModel().getValueAt(row, 3).toString());

        String  Date=(String)jTable1.getModel().getValueAt(row, 4);
        String ref=(String)jTable1.getModel().getValueAt(row, 6);

        try {
            c.updateProduit( id,Titre,pr,qt ,Date,ref);

            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void SuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppActionPerformed

        int row=jTable1.getSelectedRow();
        if(row !=-1){
            int id =(int) jTable1.getModel().getValueAt(row, 0);
            c.delete(id);
            try {
                jTable1.setModel(c.selectProduit());

            } catch (SQLException ex) {
            }
            jTable1.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);

            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            jTable1.repaint();
            jTable1.revalidate();
        }
    }//GEN-LAST:event_SuppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
         intro INTRO = new intro();
	 try {
		Thread.sleep(7000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
         INTRO.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                   
                    new ConnectionFenetre().setVisible(true);
                    try {
                        new MiniProject().setVisible(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MiniProject.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
             

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JScrollPane Ajouter;
    private javax.swing.JTextField Desc;
    private javax.swing.JScrollPane Gere_Profile;
    private javax.swing.JComboBox<String> ListeName;
    private javax.swing.JScrollPane Produits;
    private javax.swing.JTextField Quantite;
    private javax.swing.JRadioButton Rf;
    private javax.swing.JRadioButton Rp;
    private javax.swing.JRadioButton Rr;
    private javax.swing.JButton Supp;
    private javax.swing.JButton Update;
    private javax.swing.JTextField Updatemotpasse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lr;
    private javax.swing.JTextField nomUpdate;
    private javax.swing.JLabel noml;
    private javax.swing.JTextField prix;
    private javax.swing.JLabel prixl;
    private javax.swing.JLabel ql;
    private javax.swing.JTextField ref;
    // End of variables declaration//GEN-END:variables
}
